tite: WIP tessmichi website
description: >-
  I'm not sure yet what I'll put here
theme: minima

#email: your-email@example.com
baseurl: ""
url: "https://www.github.com/tessmichi/tessmichi/github/io"
twitter_username: tess_distefano
github_username:  tessmichi

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
